### ISSUE TITLE
W1070 starts blocking commands after some time

### ISSUE THREAD

**Issue by DarkStarSword** [rrooggiieerr/benqprojector.py#11]
I've submitted pull request https://github.com/rrooggiieerr/benqprojector.py/pull/10 to get this projector functional with this library in home assistant, but I'm running into an inconsistent issue where the integration starts failing after some time (becomes unavailable / fails to set up after restart), and when I manually check projector I find that it has started blocking all commands:

```
$ telnet projector-esp-link.lan
Trying 192.168.1.96...
Connected to projector-esp-link.lan.
Escape character is '^]'.

>
*pow=?#
*pow=?#

*Block item#
^]
telnet> close
Connection closed.
```

Once in this state the projector needs to be turned on with the remote / IR blaster to start working again (power cycling didn't even seem to help - only turning it on fixed it), but I'm not yet positive what is triggering this - the power commands should work while the projector is off, and I haven't encountered this issue previously when I've manually controlled the projector over serial (though that could just be because I rarely did so and just got lucky when I did).

I'm wondering if you might have seen this issue before or have any thoughts as to what to try to resolve / further diagnose it?

Some possibilities I've wondered about are if the connection is being interrupted in the middle of a command could the projector get into a bad state? I'm using socat to create a virtual tty that connects to a Wemos D1 Mini over WiFi attached to a RS232 to TTL converter plugged into the serial port, so there are definitely some extra potential points of failure there compared to a direct serial connection that I've used in the past, and I did notice some timeouts when running the 'examine' command... Another thought is could benqprojector be querying a command that had a different meaning or was bugged on the W1070 and puts it into a bad state?

I recognise that this may just end up being a BenQ firmware bug and there might not be anything you can do to help, and won't feel bad if you just close the ticket as not your problem, but any insights you may have would be appreciated.

**Comment by DarkStarSword** [comment]
Found some possibly relevant info here: https://github.com/JohnBrodie/pyjector/issues/1

Though if I'm following that right they resolved it by just waiting for the '>' before issuing the command, which wouldn't explain why it isn't working when manually issuing the command via telnet where I definitely wait for that.

**Comment by rrooggiieerr** [comment]
Hi @DarkStarSword , thanks for using my library and debugging it. My projector (W1110) is actually blocking all commands during warming up/cooling down the device. Could this also be the case in your situation?

**Comment by DarkStarSword** [comment]
That happens as well, but the issue I'm seeing is when the projector has been completely off for some time. It happened again earlier today and when I looked at the projector I noticed the power and temp lights were both flashing red, so perhaps the projector has got in some sort of error state - I didn't notice that yesterday though, so I'll keep an eye on it.

Also, it's possible that the esp-link device is causing problems since it seems to be sending boot messages over serial that might be confusing the projector. That firmware has an option to swap the serial to other pins, but that was causing other issues for me yesterday - I might go back and see if I can get that sorted at least.

**Comment by DarkStarSword** [comment]
I may have worked out what is going on here - it seems that esp-link sends its own debug logs over the serial console by default (in addition to the esp boot messages) and that was putting the projector into a bad state. So, to use esp-link to control a projector we must set:

- Home -> Pin Assignment:
-  - UART pins = swapped (i.e. use gpio15 as TX + gpio13 as RX)
-  - Other pins disabled
-  - RX pullup enabled (haven't checked if that is actually necessary)
- Debug Log:
-  - UART debug log: off

It was an inconsistent failure before, so I'll keep monitoring in case this isn't actually the correct fix, but for now I'll close this ticket.

**Comment by rrooggiieerr** [comment]
Is your ESP powered from the USB of the projector? The USB on my projector is only powered on when the projector is powered on

**Comment by DarkStarSword** [comment]
No, I've got it powered from an external USB charger
