### ISSUE TITLE
Model: mw519

### ISSUE THREAD

**Issue by LaneaLucy** [rrooggiieerr/benqprojector.py#15]
python3 -m benqprojector serial /dev/ttyUSB0 115200 examine  
Command macaddr=? not supported
Device on /dev/ttyUSB0 available
Model: mw519
Supported commands: 3d appmod asp audiosour baud bc blank bri color? con ct directpower freeze highaltitude ins lampm lpsaver ltim modelname mute pow pp qas sharp sour standbymnt vol
Supported video sources: hdmi rgb rgb2 svid vid
Supported audio sources: off rgb rgb2 vid hdmi
Supported picture modes: dynamic preset srgb cine user1 user2
Supported color temperatures: warm normal cool
Supported aspect ratios: 4:3 16:9 16:10 auto real
Supported projector positions: ft re rc fc
Supported lamp modes: lnor eco seco
Supported 3d modes: off auto tb fs fp sbs da iv
Projector configuration JSON:
{
	"commands": [
		"3d",
		"appmod",
		"asp",
		"audiosour",
		"baud",
		"bc",
		"blank",
		"bri",
		"color",
		"con",
		"ct",
		"directpower",
		"freeze",
		"highaltitude",
		"ins",
		"lampm",
		"lpsaver",
		"ltim",
		"modelname",
		"mute",
		"pow",
		"pp",
		"qas",
		"sharp",
		"sour",
		"standbymnt",
		"vol"
	],
	"video_sources": [
		"hdmi",
		"rgb",
		"rgb2",
		"svid",
		"vid"
	],
	"audio_sources": [
		"off",
		"rgb",
		"rgb2",
		"vid",
		"hdmi"
	],
	"picture_modes": [
		"dynamic",
		"preset",
		"srgb",
		"cine",
		"user1",
		"user2"
	],
	"color_temperatures": [
		"warm",
		"normal",
		"cool"
	],
	"aspect_ratios": [
		"4:3",
		"16:9",
		"16:10",
		"auto",
		"real"
	],
	"projector_positions": [
		"ft",
		"re",
		"rc",
		"fc"
	],
	"lamp_modes": [
		"lnor",
		"eco",
		"seco"
	],
	"3d_modes": [
		"off",
		"auto",
		"tb",
		"fs",
		"fp",
		"sbs",
		"da",
		"iv"
	],
	"menu_positions": []
}

**Comment by rrooggiieerr** [comment]
Your model should now be supported by the library and the HA integration
