### ISSUE TITLE
W4000i / HT4550i support

### ISSUE THREAD

**Issue by omelettedufromagee** [rrooggiieerr/benqprojector.py#24]
Hi,

I'm trying to make your component work with the fairly recent model W4000i (or HT4450i in US).

I install the python lib to do some testing:
`python -m benqprojector telnet 192.168.86.234 8000 status --debug
2024-10-25 13:50:15,632 ERROR    Failed to get projector command prompt, is your projector properly connected?
2024-10-25 13:50:15,632 ERROR    Failed to connect to BenQ projector`

From Home Assistant:
`Logger: benqprojector.benqprojector
Source: custom_components/benqprojector/config_flow.py:224
integration: benqprojector ([documentation](https://github.com/rrooggiieerr/homeassistant-benqprojector), [issues](https://github.com/rrooggiieerr/homeassistant-benqprojector/issues))
First occurred: 4:57:59 AM (21 occurrences)
Last logged: 1:04:37 PM`

`Timeout while waiting for response
Unable to retrieve projector power state: Response timeout for command 'pow' and action '?'
No command echo received
Unexpected response format, response: <cross-domain-policy>
Unable to retrieve projector power state: Invalid response for command 'pow' and action '?'. response: <cross-domain-policy>`

I'm not sure why the projector is returning some html. Maybe your component is testing other ports.

However, using PuTTy, I can telnet to the projector and execute command and get responses:
![benq-telnet](https://github.com/user-attachments/assets/5f84f4cf-ca56-43a7-a6af-2795ec45cd2e)

Any idea what I could do to debug? I should be able to do a JSON config file for this model once it's working.

**Comment by rrooggiieerr** [comment]
You're right, it was on the wrong git, bit I could transfer the issue to the right one

**Comment by rrooggiieerr** [comment]
Yes, #22 had the same issue, but I never got feedback if my changes made any difference

**Comment by rrooggiieerr** [comment]
I still like to know why `_detect_prompt` is not being called or what's going wrong there

**Comment by omelettedufromagee** [comment]
I realized that I was using a previous version of benqprojector because of my python version. I still have issues but I will update the PR https://github.com/rrooggiieerr/benqprojector.py/pull/22
