### ISSUE TITLE
lamp time cannot be processed on W1100

### ISSUE THREAD

**Issue by pkoevesdi** [rrooggiieerr/benqprojector.py#5]
With `python3 -m benqprojector /dev/virtualcom0 9600 examine --debug`, the lamp time cannot be processed, maybe because of the space before the number or the missing `#` after? For the latter see also https://github.com/rrooggiieerr/benqprojector.py/issues/6
```
2023-01-15 06:41:58,107 DEBUG    command *ltim=?#
2023-01-15 06:41:58,157 DEBUG    Response: 
2023-01-15 06:41:58,158 DEBUG    Empty line
2023-01-15 06:41:58,208 DEBUG    Response: 
2023-01-15 06:41:58,208 DEBUG    Empty line
2023-01-15 06:41:58,259 DEBUG    Response: *ltim=?#
2023-01-15 06:41:58,259 DEBUG    Command successfully send
2023-01-15 06:41:58,260 DEBUG    Response: 
2023-01-15 06:41:58,260 DEBUG    Empty line
2023-01-15 06:41:58,311 DEBUG    Response: *ltim= 1383
2023-01-15 06:41:58,311 DEBUG    LC Response: *ltim= 1383
2023-01-15 06:41:58,311 DEBUG    Raw response: '*ltim= 1383'
2023-01-15 06:41:58,312 ERROR    Unexpected response format, response: *ltim= 1383
```
See also https://github.com/rrooggiieerr/homeassistant-benqprojector/issues/4#issuecomment-1383065138

**Comment by rrooggiieerr** [comment]
@pkoevesdi, the regex is used to validate the response.

According to the BenQ documentation the response should be *<command>=<value>#. On my own projector I already noticed that one command does not respond with a leading *. I will lossen the regex a bit by also making the leading # optional. Making the = optional is a bit more complex. Do you have an example when this happens?

**Comment by pkoevesdi** [comment]
You comment would belong to the regex issue, but I cannot find it any more, did You delete it again? To me, the regex issue seems a different thing than the lamp parsing.
Example for missing `=`:
`echo -e "\r*up#\r" > /dev/virtualcom0`
Answer:
`*up#`

**Comment by rrooggiieerr** [comment]
Ah, allright, I thought you recreated the regex issue, but this one is indeed about he lamp. Yes, I deleted the other one

**Comment by pkoevesdi** [comment]
Ok, let's split it up: Do You recreate the regex issue? I'll make another one for the menu thing.

**Comment by rrooggiieerr** [comment]
I think you should be the owner for both issues

**Comment by pkoevesdi** [comment]
> I think you should be the opener for both issues

I thought there's a recover function for a deleted issue. But no problem, I recreate it and creat the other one for the menu command.

**Comment by rrooggiieerr** [comment]
Ok, getting back to the lamp parsing, this is actually also a regex issue since the missing `#` is why the response is considered invalid. The space is also not really expexted, or at least the BenQ documentation doesn't mention it, however the code doesn't really care when converting the response to an integer.

New version of the code now has a more lose regex

**Comment by pkoevesdi** [comment]
Ok, thank You for implementing.
Now I get this:
```
2023-01-15 18:23:37,973 DEBUG    Processed response:  1386
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gauner/.local/lib/python3.10/site-packages/benqprojector/__main__.py", line 43, in <module>
    projector.update()
  File "/home/gauner/.local/lib/python3.10/site-packages/benqprojector/benqprojector.py", line 618, in update
    self.lamp_time = int(response)
ValueError: invalid literal for int() with base 10: '\x00 1386'
```
Seems like something is still before the lamp hours number?

**Comment by pkoevesdi** [comment]
Ok, I replaced all `int(###)` with `int(re.sub('[^0-9]','', ###))` inside `benqprojector.py`. Now many of the problematic numbers work. One exception occurs: my projector answers some commands the follwing way: first repeating the command, and then answering with the value:
```
>*bri=?#

*bri=?#

*bri= 51
```
This is at least true for `*bri=?#`, `*con=?#`, `*color=?#`, `*sharp=?#`,...

**Comment by rrooggiieerr** [comment]
I'm also doing development on the library at the moment, and the trailing spaces have been fixed by stripping of the spaces before returning the response.

Commands are not really repeated, but echoed instead. The first line you read is the echo of the command. Hence the detection of command echoes in the code. By the way, not all projectors seem to echo the commands. The code tries to detect is command echoes are used by the projector.

**Comment by pkoevesdi** [comment]
I see, but seemingly doesn't work here. :-(

**Comment by rrooggiieerr** [comment]
Just give me some time to finish some code and commit what I'm woking on. I'll get back to you

**Comment by pkoevesdi** [comment]
> Commands are not really repeated, but echoed instead. The first line you read is the echo of the command. 

Yes, the first line is the echo, after the `>`. What I wanted to say is: There's a second echo for some commands. Compare `ltim`, echoed once, and `bri`, echoed twice.
I've made some changes too, now the `examine` and `status` commands run well on my side. I can make a pull request, or wait, what You've got.

**Comment by rrooggiieerr** [comment]
I'm finished with making my changes. If you could test my code and if needed add your changes and a pull request

**Comment by pkoevesdi** [comment]
Ok, I'll do it. 
Just some things I figured out, take it as a note to myself: 
- Everything runs more stable with higher timeout. 
- Some commands in `examine` (mostly some the "illegal format" ones) end up with a command prompt, some don't. If they do, from then on the script gets out of step and almost everything afterwards fails. Have to look for a way to figure out this condition and exit command prompt from projector first, before issuing the next command (which puts him into command prompt again by beginning with `\r`).

**Comment by rrooggiieerr** [comment]
Good points.

The timeout is to be 50 milliseconds on line 19 of `benqprojector.py`. This timeout seems to work fine for my projector and that's why I took that value. Might very well be that other models need other timeouts. The thing is that with a higher value retrieving the status of the projector can become exponentially slower.
