### ISSUE TITLE
Some commands do not provide reading

### ISSUE THREAD

**Issue by pkoevesdi** [rrooggiieerr/benqprojector.py#7]
Some commands don't provide reading, they can only be written. 
Example: `\r*menu=?#\r` on Benq W1100 doesn't work, but `\r*menu=on#\r` and `\r*menu=off#\r` do very well.

For them, the function `examine` doesn't work correctly, it reports false negative:
```
2023-01-15 06:41:59,485 DEBUG    command *menu=?#
2023-01-15 06:41:59,536 DEBUG    Response: 
2023-01-15 06:41:59,536 DEBUG    Empty line
2023-01-15 06:41:59,586 DEBUG    Response: 
2023-01-15 06:41:59,587 DEBUG    Empty line
2023-01-15 06:41:59,638 DEBUG    Response: *menu=?#
2023-01-15 06:41:59,638 DEBUG    Command successfully send
2023-01-15 06:41:59,638 DEBUG    Response: 
2023-01-15 06:41:59,639 DEBUG    Empty line
2023-01-15 06:41:59,690 DEBUG    Response: Unsupported item
2023-01-15 06:41:59,690 DEBUG    LC Response: unsupported item
2023-01-15 06:41:59,690 DEBUG    Raw response: 'unsupported item'
2023-01-15 06:41:59,691 ERROR    Unexpected response format, response: unsupported item
```

**Comment by rrooggiieerr** [comment]
It's actually a bit difficult to detect if a command is supported if the status can not be requested. In that case the real command should be tested which changes the state of the projector. If it makes sense what I'm saying

For instance when I'm detecting the supported input sources I first request the current source, then try all know source types and at the end set the source type back to the original source. This way I'm leaving the projector in it's original state after the detection has been finished.

If I'm not able to request the current state of a feature I'm also not able to return to this state after the detection has been finished.

**Comment by rrooggiieerr** [comment]
For showing and navigating the menu, the whole idea of using a library is to not having to use the menu. So I'm thinking about not supporting those commands all together. Do you see a use case for using and navigating the menu with the library?

**Comment by rrooggiieerr** [comment]
What I'm also noticing is that your projector returns `Unsupported item` when a command is not supported while my projector returns `*Unsupported item#`

**Comment by pkoevesdi** [comment]
Ich see a use case: Having a remote control on the mobile phone. I could make an remote control card inside home assistant and fully control the projector. But it's a lot of work and i would prioritize this low. If the internal commands (beside navigating in the menu) work, I would be very happy already.

**Comment by pkoevesdi** [comment]
Also, one more thing: `enter` and the navigation keys are also used to go into shift mode and then shift the picture left/right/up/down if zoomed in.

**Comment by pkoevesdi** [comment]
> I created a function to send raw commands. 

I saw it already. :-)

> Do you think this is a workable solution?

I think so. If everything works in general I'll check it out. Thank You!

**Comment by rrooggiieerr** [comment]
Hi @pkoevesdi , I'm guessing the items mentioned in this issue are now resolved/covered so I can close the issue?

Please reopen if you think that's not the case.

Thanks!

**Comment by pkoevesdi** [comment]
Just a short comment: I can imagine, it's fixed, You took some commands into an ignore list, can be a good workaround. I haven't checked yet, if this list is complete or too harsh for my projector.

I have only few time, last weekend I spend my very few hours it with putting together your last commit and what I did that week before.
My aim is to get `examine` to comletely work with my projector. At the moment (after some tweaks to your current commit, I will PR them as soon I have them ready), it runs through without error, but still gives some false positives for some commands. I'll keep on developing it further to make it work for w1100, hopefully without breaking other projectors.

**Comment by rrooggiieerr** [comment]
Ok, thanks for the heads up. Looking forward to your improvements
